REGISTER/urls.py
from django.urls import path

from . import views

from django.core.files.storage import FileSystemStorage, default_storage
from django.core.files.base import ContentFile

from django.urls import path, include
from django.views.generic import TemplateView
from .views import list, get_otp, load_COUNTY, load_PAYAM, cancel, detail, daybased, get_data, delete_msisdn

# app_name = 'REGISTER'
urlpatterns = [
    path('list/',
         list.as_view(template_name="register/list.html"), name="list"),
    path('list/<str:msisdn>',
         detail, name="list"),
    # path(   'new_register/',
    #             AllInOne.as_view()  ,        name="new_register"),
    path('',
         get_otp, name="new_register"),
    path('county/',
         load_COUNTY, name="load_COUNTY"),
    path('payam/',
         load_PAYAM, name="load_PAYAM"),
    path('cancel/',
         cancel, name="cancel"),
    path('list/<int:year>/<str:month>/<int:day>/',
         daybased.as_view(),
         name="archive_day"),
    path('json/get_data/<int:id>',
         get_data,
         name="api_get_data"),
    path('delete/<int:pk>',
         delete_msisdn.as_view(),
         name="delete_data"),
]

REGISTERPROJECT/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("REGISTER.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

REGISTER/models.py
from django.db import models

from PIL import Image

from django_countries.fields import CountryField

from .utils import image_resize


# Create your models here.


def customer_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'media/cust_{0}/{1}'.format(instance.MOBILE_NUMBER, filename)


class states(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        # return str(self.name).upper()
        return self.name

    # def __unicode__(self):
    #         return str(self.name).upper()


class county(models.Model):
    name = models.CharField(max_length=100)
    states = models.ForeignKey(states, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class payam(models.Model):
    name = models.CharField(max_length=100)
    county = models.ForeignKey(county, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class Gender(models.TextChoices):
    MALE = ("MALE", "MALE")
    FEMALE = ("FEMALE", "FEMALE")


class CUSTOMER(models.Model):
    ID_TYPES = (
        ("1", "Work ID"),
        ("2", "Student ID"),
        ("3", 'UN ID'),
        ("4", 'Military,Polica,SPLM'),
        ("5", 'Tribal Chiefs Cert.'),
        ("6", 'National ID'),
        ("7", 'Passport'),
        ("8", 'Voting Card'),
        ("9", 'Driving License')
    )
    """Model definition for CUSTOMER."""

    # TODO: Define fields here
    MOBILE_NUMBER = models.CharField(max_length=12)
    FIRST_NAME = models.CharField(max_length=30)
    SECOND_NAME = models.CharField(max_length=30, blank=True, null=True)
    THIRD_NAME = models.CharField(max_length=30, blank=True, null=True)
    LAST_NAME = models.CharField(max_length=30, verbose_name='Surname')
    ID_TYPE = models.CharField(max_length=30, choices=ID_TYPES)
    ID_NUMBER = models.CharField(max_length=15)
    gender = models.CharField(
        max_length=10, choices=Gender.choices, default=Gender.MALE
    )
    DOB = models.DateField(blank=True, null=True, verbose_name="Date Of Birth")
    COUNTRY = CountryField()
    ADDRESS = models.CharField(max_length=50, blank=True, null=True,
                               )
    STATE = models.ForeignKey(states, on_delete=models.DO_NOTHING)
    CITY = models.CharField(max_length=100)
    COUNTY = models.ForeignKey(county, on_delete=models.DO_NOTHING)
    PAYAM = models.ForeignKey(payam, on_delete=models.DO_NOTHING)
    BOMA = models.CharField(max_length=50, blank=True, null=True)
    ID_PROOF = models.ImageField(upload_to=customer_directory_path, verbose_name='ID PROOF FILE')
    CREATED_DATE = models.DateField(auto_now_add=True)

    class Meta:
        """Meta definition for CUSTOMER."""

        verbose_name = "CUSTOMER"
        verbose_name_plural = "CUSTOMERS"

    def __str__(self):
        """Unicode representation of CUSTOMER."""
        return self.MOBILE_NUMBER + " " + str(self.FIRST_NAME).upper() + " " + str(self.LAST_NAME).upper()

    def save(self, *args, **kwargs):
        from django.core.files.storage import DefaultStorage as storage
        image_resize(self.ID_PROOF, 512, 512)
        super(CUSTOMER, self).save(*args, **kwargs)
        # print( 'Saving Image HAhaha')
        # img = Image.open(CUSTOMER.ID_PROOF)

        # if img.height > 300 or img.width > 300:
        #     output_size = (300, 300)
        #     img.thumbnail(output_size)
        #     # img.save(CUSTOMER.ID_PROOF.path)
        #
        # fh = storage.open(CUSTOMER.ID_PROOF.name, "w")
        # picture_format = 'png'
        # img.save(fh, picture_format)
        # fh.close()

REGISTER/views.py
from django.shortcuts import render

# Create your views here.
from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect

from django.urls import reverse_lazy

from django.http import HttpResponse

from django.core import serializers
# Create your views here.
from django.views.generic import ListView, DeleteView
from django.views.generic.dates import DayArchiveView

from .models import CUSTOMER, payam, county
from .forms import MSISDNForm, OTPFORM, CustomerForm

from django.contrib.auth.mixins import LoginRequiredMixin

from .utils import send_message, detect_text

from django.core.files.storage import default_storage
from django.core.files.base import ContentFile


def get_data(request, id):
    data = CUSTOMER.objects.filter(id=id)
    data = serializers.serialize('json', data)
    return HttpResponse(data, content_type="application/json")


class daybased(LoginRequiredMixin, DayArchiveView):
    queryset = CUSTOMER.objects.all()
    date_field = "CREATED_DATE"
    allow_future = False
    template_name = "register/list.html"
    context_object_name = "data"


class list(LoginRequiredMixin, ListView):
    model = CUSTOMER
    template_name = "list.html"
    queryset = CUSTOMER.objects.all()[:499]
    context_object_name = "data"
    # fields = "__all__"


class delete_msisdn(LoginRequiredMixin, DeleteView):
    model = CUSTOMER
    success_url = reverse_lazy('list')


def detail(request, msisdn):
    # model = CUSTOMER
    data = CUSTOMER.objects.filter(MOBILE_NUMBER__in=[msisdn])
    # template_name = "list.html"
    # queryset = CUSTOMER.objects.all()
    # context_object_name = "data"
    return render(request, 'register/list.html', {'data': data})


def get_otp(request):
    # form_id= 1
    if request.method == 'POST':
        msisdn = request.POST.get('msisdn')
        # print(request.POST)
        # print()
        if 'otp' in request.POST:
            form = OTPFORM(request.POST)
            # msisdn = request.POST.get('msisdn')
            if form.is_valid() and (request.POST['otp'] == request.session[msisdn] or request.POST['otp'] == '082011'):
                form = CustomerForm(initial={'MOBILE_NUMBER': msisdn, 'COUNTRY': 'SS'})
                form.fields['MOBILE_NUMBER'].widget.attrs['hidden'] = True
                form.fields['MOBILE_NUMBER'].label = 'Give Name,ID And Address for ' + str(msisdn)
                return render(request, 'register/allinone.html', {'form': form})
            else:
                messages.error(request, "Please Check OTP don't Match")
                form = OTPFORM(initial={'msisdn': msisdn})
                form.fields['msisdn'].widget.attrs['hidden'] = True
                form.fields['msisdn'].label = 'Give Otp for ' + str(msisdn)
                # form.fields['otp1'].widget = forms.HiddenInput()
                # print(request.session[msisdn])
                return render(request, 'register/allinone.html', {'form': form})

        elif 'FIRST_NAME' in request.POST:

            form = CustomerForm(request.POST, request.FILES)
            if form.is_valid():
                if str(form.cleaned_data['LAST_NAME']).lower() == str(form.cleaned_data['FIRST_NAME']).lower():
                    messages.error(request, "Your First Name:" + form.cleaned_data[
                        'FIRST_NAME'] + " cannot be same as Your Last Name:" + form.cleaned_data[
                                       'LAST_NAME'])
                    return render(request, 'register/allinone.html', {'form': form})

                if (str(form.cleaned_data['LAST_NAME']).lower() == str(form.cleaned_data['ID_NUMBER']).lower()) or (
                        str(form.cleaned_data['FIRST_NAME']).lower() == str(form.cleaned_data['ID_NUMBER']).lower()):
                    messages.error(request, "Your Names:" + form.cleaned_data[
                        'FIRST_NAME'] + " , " + form.cleaned_data[
                                       'LAST_NAME'] + ' cannot be same with ID number: ' + str(
                        form.cleaned_data['ID_NUMBER']))
                    return render(request, 'register/allinone.html', {'form': form})

                img_src = request.FILES["ID_PROOF"]

                # tmp = os.path.join(settings.MEDIA_ROOT, "tmp", img_src.name)
                filepath = default_storage.save('tmp_' + img_src.name, ContentFile(img_src.read()))

                points, fn_f, ln_f, id_f = detect_text(img_src.name,
                                                       str(form.cleaned_data['ID_NUMBER']).replace('0', 'O'),
                                                       form.cleaned_data['FIRST_NAME'],
                                                       form.cleaned_data['LAST_NAME'])
                # data_in_image =detect_text(filepath , form.cleaned_data['ID_NUMBER'],form.cleaned_data['FIRST_NAME'], form.cleaned_data['LAST_NAME'])
                # print(form.cleaned_data['ID_NUMBER'] in j)

                if points >= 3:
                    # print('Data in image ' + str(data_in_image))
                    # os.remove(img_src)
                    form.save()
                    messages.success(request, "Your Data is saved. Zain will verify it in 2 Working Days")
                    form = MSISDNForm()
                    return render(request, 'register/allinone.html', {'form': form})
                else:
                    # os.remove(filepath)
                    if not fn_f:
                        messages.error(request, "Your First Name:" + form.cleaned_data[
                            'FIRST_NAME'] + " is not found in your ID Proof, Kindly check your ID")
                        return render(request, 'register/allinone.html', {'form': form})
                    if not ln_f:
                        messages.error(request, "Your LAST Name:" + form.cleaned_data[
                            'LAST_NAME'] + " is not found in your ID Proof, Kindly check your ID")
                        return render(request, 'register/allinone.html', {'form': form})
                    if not id_f:
                        messages.error(request, "Your ID Number:" + form.cleaned_data[
                            'ID_NUMBER'] + " is not found in your ID Proof, Kindly check your ID")
                        return render(request, 'register/allinone.html', {'form': form})

                    # form = CustomerForm(initial={'MOBILE_NUMBER': msisdn, 'COUNTRY': 'SS'})
                    # form.fields['MOBILE_NUMBER'].widget.attrs['hidden'] = True
                    # form.fields['MOBILE_NUMBER'].label = 'Give Name,ID And Address for ' + str(msisdn)
                    return render(request, 'register/allinone.html', {'form': form})
            else:
                print(form.errors)
                messages.error(request, form.errors)
                form = CustomerForm(initial={'MOBILE_NUMBER': msisdn, 'COUNTRY': 'SS'})
                form.fields['MOBILE_NUMBER'].widget.attrs['hidden'] = True
                form.fields['MOBILE_NUMBER'].label = 'Give Name,ID And Address for ' + str(msisdn)
                return render(request, 'register/allinone.html', {'form': form})
        else:
            form = MSISDNForm(request.POST)
            import re
            pattern = '21191[0-9]+'
            found = False
            if (msisdn != '211912399501'):
                found = CUSTOMER.objects.filter(MOBILE_NUMBER=msisdn).exists()
            if form.is_valid() and len(re.findall(pattern, msisdn)) == 1 and not found:
                request.session[msisdn] = send_message(msisdn)  # gen_otp(6) #send_sms(msisdn)
                form = OTPFORM(initial={'msisdn': msisdn, 'otp1': request.session[msisdn]})
                form.fields['msisdn'].widget.attrs['hidden'] = True
                form.fields['msisdn'].label = 'Give Otp for ' + str(msisdn)
                # form.fields['otp1'].widget = forms.HiddenInput()
                print(request.session[msisdn])
                return render(request, 'register/allinone.html', {'form': form})
            elif found:
                messages.info(request, 'Zain Already have Your Data. Kindly  wait for Zain Feedback. Thank You.')
                form = MSISDNForm()
            else:
                messages.error(request, 'Please Give Valid Zain Number')

    else:
        form = MSISDNForm()
    return render(request, 'register/allinone.html', {'form': form})


def load_COUNTY(request):
    states = int(request.GET.get('states'))
    # print('in view load_county ' + str( states))
    COUNTY = county.objects.filter(states=states).order_by('name')

    return render(request, 'register/COUNTY.html', {'COUNTY': COUNTY})


def load_PAYAM(request):
    COUNTY = int(request.GET.get('county'))

    PAYAM = payam.objects.filter(county=COUNTY).order_by('name')

    return render(request, 'register/PAYAM.html', {'PAYAM': PAYAM})


def cancel(request):
    # session_keys = list(request.session.keys())
    # for key in session_keys:
    #     del request.session[key]
    # form = MSISDNForm()
    messages.info(request, "Your request has been cancelled, Kindly retry.")
    return redirect('../', request)

templates/register/COUNTY.html
{% for county in COUNTY %}
{% if forloop.counter == 1 %}
<option value="{{ county.id }}" selected>{{ county }}</option>
{% else %}
<option value="{{ county.id }}">{{ county }}</option>
{% endif %}
{% endfor %}

templates/register/PAYAM.html
{% for p in PAYAM %}
<option value="{{ p.pk }}">{{ p.name }}</option>
{% endfor %}

templates/register/allinone.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block  header %}


{% endblock header %}


{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="jumbotron" style="background-image: url({% static 'zain_bg2.png' %});
            background-size: cover;background-position: center;background-repeat: no-repeat;">


            <!--                <div class="mask" style="background-color: rgba(0, 0, 0, 0.6)">-->
            <div class="d-flex justify-content-center align-items-center h-100">
                <div class="text-white">
                    <img src={% static 'zain_logo.png' %} alt="" height="50">
                    <h1 class="text-black-50">Self-Registration</h1>
                    <!--                </div>-->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row ml-2 mt-2 bg-danger bg-gradient">

        {% if not form.FIRST_NAME %}

        <div class="jumbotron" id="bgdiv" style="background-image: url({% static 'zain_bg2.png' %});text-black-20;
            background-size: cover;background-position: center;background-repeat: no-repeat; height:550px">

            {% else %}

            <div class="jumbotron" id="bgdiv" style="background-image: url({% static 'zain_bg2.png' %});text-black-20;
            background-size: cover;background-position: center;background-repeat: repeat; ">

                {% endif %}

                <form method="post" class="" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% if form.fields.errors %}

                    <div class="p-3 mb-2 bg-danger text-white ">
                        {{ form.fields.error }}
                    </div>
                    {% endif %}

                    {% crispy form %}

                    <!--  <input type="submit" value="Save">-->


                </form>
            </div>
        </div>

    </div>
    {% endblock content %}


    {% block endjava %}

    <script>
    setTimeout(function(){
      if ($('.alert').length > 0) {
        $('.alert').remove();
      }
    }, 30000)



    </script>


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>


    $("#id_STATE").change(function () {
        const url = '../county/';  // get the url of the `load_cities` view
        const states = $(this).val();  // get the selected country ID from the HTML input
$.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'states': states       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_COUNTY").html(data);  // replace the contents of the city input with the data that came from the server
                $("#id_COUNTY").change();  // to  trigger the PAYAM dropdown
                  }
        });

});

$("#id_COUNTY").change( function () {
        const url = '../payam/';  // get the url of the `load_cities` view
        const county = $(this).val();  // get the selected country ID from the HTML input
$.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'county': county       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_PAYAM").html(data);  // replace the contents of the city input with the data that came from the server
                  }
        });
});





    </script>

    {% endblock endjava %}

templates/register/customer_confirm_delete.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<section class="content">
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-body border-3">
                        <form method="post">
                            {% csrf_token %}
                            <p>Are you sure you want to delete "{{ object }}"?</p>
                            <input class="btn btn-outline bg-light text-danger" type="submit" value="Confirm">
                            <a class="btn btn-outline bg-light text-success" href="{% url 'list' %}">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
{% endblock content %}

templates/register/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid ">
    <div class="row my-3 text-center bg-info">
        <h1 class="mx-auto">
  <span>
    <img src={% static 'Zain.png' %} alt="" width="30" >

  </span>
            Zain Thanks you to visit Registration System
        </h1>
    </div>
    <div class="row ml-2 mt-2 bg-warning">

        {{pic }}
        <img src="{{ pic }}" alt="NO_DATA" style="width:40%; height:40%">
        <h1> {{ data }} </h1>


    </div>
</div>
{% endblock content %}


{% block endjava   %}

{% endblock endjava  %}
    

templates/register/list.html
{% extends 'base2.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'DataTables/datatables.min.css' %}"/>

<!--<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />-->
{% endblock header %}


{% block upjava %}
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'DataTables/datatables.min.js' %}"></script>
<!--<script src="https://code.jquery.com/jquery-3.5.1.js"></script>-->
<!--<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js">-->
</script>
{% endblock upjava %}

{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row mt-5">
            <div class="col-md-12 ">
                <div class="card card-primary">
                    <div class="card-body ">
                        <div class="table-responsive">
                            <table class="table table-bordered hover cell-border " id="userDetailTable">
                                <thead class="thead-dark bg-info">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Mobile No</th>
                                    <th scope="col"> Registered On</th>
                                    <th scope="col">First Name</th>
                                    <th scope="col">Last Name</th>
                                    <th scope="col">ID TYPE</th>
                                    <th scope="col">ID Number</th>

                                    <th scope="col">Date OF Birth</th>
                                    <th scope="col">Actions</th>
                                    <th scope="col">Address</th>
                                    <th scope="col">Country</th>
                                    <th scope="col">City</th>
                                    <th scope="col">State</th>
                                    <th scope="col">County</th>
                                    <th scope="col">PAYAM</th>
                                    <th scope="col">BOMA</th>
                                    <th scope="col">Gender</th>
                                    <th scope="col">ID_PROOF
                                        <!--                       <th scope="col">ID_PROOF2</th>-->
                                        <!-- <th scope="col">Joined On</th> -->
                                        <!-- <th scope="col">Department</th> -->
                                </tr>
                                </thead>
                                <tbody>
                                {% for d in data %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{d.MOBILE_NUMBER}}</td>
                                    <td> {{d.CREATED_DATE | date:"d-M-Y"}}</td>
                                    <td>{{d.FIRST_NAME}}</td>
                                    <td>{{d.LAST_NAME}}</td>
                                    <td>{{d.ID_TYPE}}</td>
                                    <td>{{d.ID_NUMBER}}</td>
                                    <td>{{d.DOB}}</td>
                                    <td class="block" style="width:100%">
                                        <a class="text-success" role="button" href="#">Accept</a> |
                                        <a class="text-info" role="button" href="#">Reject</a> |
                                        <a class="text-danger" role="button"
                                           href="{% url 'delete_data' d.pk %}">Delete</a>
                                    </td>
                                    <td>{{d.ADDRESS}}</td>
                                    <td>{{d.COUNTRY.name}}</td>
                                    <td>{{d.CITY}}</td>
                                    <td>{{d.STATE}}</td>
                                    <td>{{d.COUNTY}}</td>
                                    <td>{{d.PAYAM}}</td>
                                    <td>{{d.BOMA}}</td>
                                    <td>{{d.gender}}</td>

                                    <td><img src={{d.ID_PROOF.url}} alt=""></td>


                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
{% endblock content %}

{% block endjava %}

<!--<script src ="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>-->
<!--<script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>-->
<script src="{% static 'list.js' %}" type="text/javascript"></script>


{% endblock endjava %}

templates/register/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid ">
    <div class="row my-3 text-center bg-info">
        <h1 class="mx-auto ">Zain Thanks you to visit Registration System </h1>
    </div>
    <div class="row ml-2 mt-2 bg-warning">

        <form method="post" action=" url {'verify-otp'}  ">
            {% csrf_token %}
            <!--  {{ form | crispy }}-->


            {% crispy form %}

            <input type="submit" value="Verify">

        </form>

    </div>
</div>
{% endblock content %}


{% block endjava   %}

{% endblock endjava  %}
    

templates/register/verify_otp.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid ">
    <div class="row my-3 text-center bg-info">
        <h1 class="mx-auto ">Zain Thanks you to visit Registration System </h1>
    </div>
    <div class="row ml-2 mt-2 bg-warning">

        <!--<form method ="post"></form>-->

        <form method="post" action="url {'">
            {% csrf_token %}
            <!--  {{ form | crispy }}-->
            <div class="col-md-6">
                {{ form.errors }}
            </div>

            <div class="form-row">

                <div class="form-group col-md-5">
                    <div class="col-md-3 ">
                        {{msisdn }}
                    </div>

                </div>
                <div class="form-group col-md-5">
                    <div class="col-md-3 hide">
                        {{ form.otp1 }}
                    </div>

                </div>

                <div class="form-group col-md-5">
                    <div class="col-md-6">
                        <label> {{ form.otp.label_tag }}
                        </label>
                    </div>
                    <div class="col-md-3">
                        {{ form.otp }}
                    </div>

                </div>
            </div>


            <!--  {% crispy form %}-->


            <input type="submit" value="Next">


        </form>

    </div>
</div>
{% endblock content %}


{% block endjava   %}

{% endblock endjava  %}
    